//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base_EventsPoster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients_Event_
    {
        public int Id { get; set; }
        public int Event_id { get; set; }
        public int Client_Id { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Purchase_date { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Event_ Event_ { get; set; }
    }
}
